SpoonLabs/astor

src/main/java/fr/inria/astor/core/loop/spaces/ingredients/ingredientSearch/CloneIngredientSearchStrategy.java
Remove two unused imports and ensure granularity is lowercase IAW file
names
=> Edit CloneIngredientSearchStrategy.java

src/main/java/fr/inria/astor/core/loop/spaces/ingredients/ingredientSearch/CloneIngredientSearchStrategy.java, src/main/java/fr/inria/astor/core/loop/spaces/ingredients/ingredientSearch/EfficientIngredientStrategy.java, src/main/java/fr/inria/astor/core/manipulation/sourcecode/VariableResolver.java
Use learningdir for path to clustering file
=> Edit VariableResolver

src/main/java/fr/inria/astor/core/loop/spaces/ingredients/ingredientSearch/CloneIngredientSearchStrategy.java
Tweak type filters and improve logging
=> Edit CloneIngredientSearchStrategy

.travis-settings.xml, .travis.yml, pom.xml
each release will be pushed here: https://github.com/tdurieux/maven-repository
The goal is to include astor in https://github.com/Spirals-Team/maven-repair.
=> Automatically release each push on master

.travis.yml
=> Fix travis.yml for deploying Astor

.travis.yml
=> release on Maven Durieux with commit id

src/test/java/fr/inria/astor/test/repair/evaluation/extensionpoints/ingredients/IngredientPoolTest.java
Add test for MaxLcsSimSearchStrategy in PR #97.
=> Add test for MaxLcsSimSearchStrategy

src/test/java/fr/inria/astor/test/repair/evaluation/extensionpoints/ingredients/IngredientPoolTest.java, src/test/java/fr/inria/astor/test/repair/evaluation/extensionpoints/ingredients/MaxLcsSimSearchStrategy.java
-removing duplicate code (method getLcsSimilarity was in both test and
ingredient selection strategy )
-adding an assertion about the loaded strategy
-applying code format
-removed not used packages from namespace
=> [minor] minor changes on ingredient selection strategies

src/main/java/fr/inria/main/AbstractMain.java
Fix when running astor with -fitnessfunction argument
=> fitnessfunction fix

src/main/java/fr/inria/astor/core/solutionsearch/spaces/ingredients/transformations/ProbabilisticTransformationStrategy.java
parameter instead of creating a new one.
=> [bugfix] if not transformation, passing the ingredients received as

src/main/java/fr/inria/astor/core/setup/ProjectConfiguration.java, src/main/java/fr/inria/astor/core/setup/ProjectRepairFacade.java, src/main/java/fr/inria/main/AbstractMain.java, src/test/java/fr/inria/astor/test/repair/core/ConfigurationTest.java
=> multi bin folder: we can pass multiple bin folders separated by the path

src/main/java/fr/inria/astor/util/PatchDiffCalculator.java, src/main/resources/configuration.properties, src/test/java/fr/inria/astor/test/repair/core/PatchDiffTest.java
=> diff: relative and git diffs

src/main/java/fr/inria/astor/core/faultlocalization/gzoltar/GZoltarFaultLocalization.java, src/main/java/fr/inria/astor/core/solutionsearch/AstorCoreEngine.java
=> [refactor] minor changes on fault localisation. i.e., changing name in

.travis.yml, src/test/java/fr/inria/astor/test/repair/QuixBugsRepairTest.java
=> Quixbugs travis

docs/getting-starting.md
FAQ how to solve GZoltar NullPointerException problem in get-start
Solve [Issue#94](https://github.com/SpoonLabs/astor/issues/94)
=> FAQ gzoltar NullPointerException problem

src/main/java/fr/inria/main/AbstractMain.java
Solves https://github.com/SpoonLabs/astor/issues/238
Signed-off-by: Javier Ron <javierron90@gmail.com>
=> Changed order of execution in AbstractMain.java

src/main/java/fr/inria/astor/core/antipattern/AntiPattern.java, src/main/java/fr/inria/astor/core/solutionsearch/EvolutionarySearchEngine.java, src/main/java/fr/inria/main/AbstractMain.java, src/main/resources/astor.properties, src/test/java/fr/inria/astor/test/repair/core/antipattern/AntiPatternDemoClass.java, src/test/java/fr/inria/astor/test/repair/core/antipattern/AntiPatternTest.java
- Related issue
- #245 
- Implemented anti-patterns
- Anti-delete control statement 
- Anti-append early exit  
- Anti-append trivial condition
=> Add anti-pattern in EvolutionarySearchEngine

pom.xml
=> migrate to log4j 2+

src/main/java/fr/inria/astor/core/solutionsearch/spaces/ingredients/transformations/ProbabilisticTransformationStrategy.java, src/test/java/fr/inria/astor/test/repair/approaches/cardumen/CardumenApproachTest.java
To understand the context of the bug see #296
=> [bug fix] Non-deterministic bug in Cardumen fixed

src/main/java/fr/inria/astor/core/solutionsearch/AstorCoreEngine.java, src/main/java/fr/inria/astor/core/solutionsearch/population/ProgramVariantFactory.java, src/main/java/fr/inria/astor/core/solutionsearch/spaces/ingredients/transformations/ProbabilisticTransformationStrategy.java, src/test/java/fr/inria/astor/test/repair/approaches/cardumen/CardumenApproachTest.java, src/test/java/fr/inria/astor/test/repair/core/solutionsearch/ProgramVariantFactoryTest.java, src/test/java/fr/inria/astor/test/repair/evaluation/regression/MathCommandsTests.java
See issue #301 
It is better to remove these elements before entering in the loop
Also removed some javadoc that was incorrect in one file
=> Remove elements with NoSourcePosition

pom.xml
This solves problems raised in #292 and #295
Astor currently gives the following error message when running:
```
ERROR StatusLogger Unrecognized format specifier [d]
ERROR StatusLogger Unrecognized conversion specifier [d] starting at position 16 in conversion pattern.
ERROR StatusLogger Unrecognized format specifier [thread]
ERROR StatusLogger Unrecognized conversion specifier [thread] starting at position 25 in conversion pattern.
```
This is a knonw issue: https://stackoverflow.com/questions/48033792/log4j2-error-statuslogger-unrecognized-conversion-specifier
With these changes, the error doesn't appear anymore
=> Fix log error "ERROR StatusLogger Unrecognized format specifier [d]"

.github/workflows/tests.yml, pom.xml, src/main/java/fr/inria/astor/core/faultlocalization/FaultLocalizationResult.java, src/main/java/fr/inria/astor/core/faultlocalization/FaultLocalizationUtils.java, src/main/java/fr/inria/astor/core/faultlocalization/flacoco/FlacocoFaultLocalization.java, src/main/java/fr/inria/astor/core/faultlocalization/gzoltar/GZoltarFaultLocalization.java, src/main/java/fr/inria/main/AbstractMain.java, src/main/resources/astor.properties, src/test/java/fr/inria/astor/test/repair/QuixBugsRepairTest.java, src/test/java/fr/inria/astor/test/repair/approaches/cardumen/CardumenApproachTest.java, src/test/java/fr/inria/astor/test/repair/approaches/cardumen/CardumenExahustiveTest.java, src/test/java/fr/inria/astor/test/repair/core/VariableResolverTest.java, src/test/java/fr/inria/astor/test/repair/evaluation/extensionpoints/FaultLocalizationExtensionTest.java, src/test/java/fr/inria/astor/test/repair/evaluation/extensionpoints/ingredients/IngredientPoolTest.java, src/test/java/fr/inria/astor/test/repair/evaluation/extensionpoints/operatorselection/RepairOperatorTest.java
=> Flacoco support

examples/math_70/pom.xml
So as to fix CI error https://ci.inria.fr/sos/job/astor/1066/console
=> chore: update test resource to work with Java 11

src/main/java/fr/inria/astor/core/faultlocalization/flacoco/FlacocoFaultLocalization.java
Fixes https://github.com/SpoonLabs/flacoco/issues/106
=> Add `java.*` to flacoco's exclude pattern

pom.xml
Attempts to fix https://github.com/SpoonLabs/flacoco/issues/106
=> Bump jacoco-maven-plugin to 0.8.7

src/main/java/fr/inria/main/AbstractMain.java
=> fixing issue 338: removing precondition that checks the jre into the jvm

pom.xml, src/main/java/fr/inria/astor/core/faultlocalization/gzoltar/NovelGZoltarFaultLocalization.java, src/main/java/fr/inria/main/AbstractMain.java, src/main/resources/astor.properties
=> Fix NovelGZoltar

README.md
Added the publication about the Figra version of Cardamom.
=> Added Figra publication
